version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend/harmonyheaven
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=mysql://symfony_user:symfony_password@database:3306/symfony_db
    depends_on:
      - database
   
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3306"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: